# Generated by Django 4.2.19 on 2026-01-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('link', models.URLField(blank=True, help_text='Введите адрес сайта организации (Не обязательно)', null=True, verbose_name='Ссылка на сайт организации')),
                ('image', models.ImageField(upload_to='client-photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery-photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото галлереи',
                'verbose_name_plural': 'Фото галлереи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=250, verbose_name='Слаг')),
                ('slug_ru', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('slug_uz', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('slug_en', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание (что было сделано)')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание (что было сделано)')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание (что было сделано)')),
                ('description_en', models.TextField(null=True, verbose_name='Описание (что было сделано)')),
                ('finished_date', models.DateField(verbose_name='Когда это было сделано')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('fullname', models.CharField(max_length=100, verbose_name='Название организации')),
                ('video', models.FileField(help_text='Видео отзыв клиента (не больше 20 MB)', null=True, upload_to='videos/', verbose_name='Видео')),
                ('is_active', models.BooleanField(default=True, help_text='Если отключить, то отзыв не будет показываться. Вместо удаления можно просто отключить видимость', verbose_name='Показывать отзыв ?')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, verbose_name='Слаг')),
                ('slug_ru', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('slug_uz', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('slug_en', models.SlugField(max_length=250, null=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('header_bg', models.ImageField(null=True, upload_to='', verbose_name='Задний фон для шапки')),
                ('description_bg', models.ImageField(null=True, upload_to='', verbose_name='Задний фон для описания')),
                ('order', models.IntegerField(default=1, help_text='Порядок показа услуги в списке услуг', verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение выполненных работ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='app_main.service')),
            ],
            options={
                'verbose_name': 'Изображение выполненных работ',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='project-photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='app_main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проект',
                'verbose_name_plural': 'Фото проектов',
            },
        ),
    ]
