# Generated by Django 5.1.5 on 2025-02-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.service')),
            ],
        ),
    ]
