# Generated by Django 5.1.5 on 2025-02-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_bg',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='header_bg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
