# Generated by Django 4.2.19 on 2025-02-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_service_description_bg_service_header_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_main.service'),
        ),
    ]
