# Generated by Django 4.2.19 on 2025-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_serviceimage_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Изображение выполненных работ', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_bg',
            field=models.ImageField(null=True, upload_to='', verbose_name='Задний фон для описания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='header_bg',
            field=models.ImageField(null=True, upload_to='', verbose_name='Задний фон для шапки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(max_length=250, null=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_uz',
            field=models.SlugField(max_length=250, null=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Изображение выполненных работ'),
        ),
    ]
