# Generated by Django 4.2.19 on 2025-11-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_galleryimage_created_galleryimage_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='updated',
        ),
    ]
