# Generated by Django 4.2.19 on 2025-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_remove_galleryimage_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='service',
            name='card_bg',
            field=models.ImageField(null=True, upload_to='', verbose_name='Задний фон для карточки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug_uz',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
    ]
