# Generated by Django 4.2.19 on 2025-11-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_alter_review_options_service_card_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='card_bg',
        ),
    ]
