# Generated by Django 4.2.19 on 2025-11-24 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_remove_service_card_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание (что было сделано)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание (что было сделано)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание (что было сделано)'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_ru',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_uz',
            field=models.SlugField(max_length=250, null=True, verbose_name='Слаг'),
        ),
    ]
