# Generated by Django 4.2.19 on 2025-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_project_description_en_project_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='description_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='description_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='description_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
