# Generated by Django 4.2.19 on 2025-11-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_galleryimage_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.URLField(help_text='Введите адрес сайта организации (Не обязательно)', null=True, verbose_name='Ссылка на сайт организации'),
        ),
    ]
