# Generated by Django 4.2.19 on 2025-11-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_client_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.URLField(blank=True, help_text='Введите адрес сайта организации (Не обязательно)', null=True, verbose_name='Ссылка на сайт организации'),
        ),
    ]
