# Generated by Django 4.2.19 on 2025-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_alter_client_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description_uz',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='description_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='description_uz',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
