# Generated by Django 4.2.19 on 2025-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_alter_galleryimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать отзыв ?'),
        ),
    ]
