# Generated by Django 4.2.19 on 2025-12-02 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_review_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, help_text='Фидео отзыв клиента (не больше 20 MB)', upload_to='videos/', verbose_name='Фидео'),
            preserve_default=False,
        ),
    ]
