# Generated by Django 4.2.19 on 2025-11-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_review_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='contacts',
            field=models.CharField(blank=True, help_text='Telegram username, Номер телефона, E-mail, ...', max_length=100, null=True, verbose_name='Контакты'),
        ),
    ]
