# Generated by Django 4.2.19 on 2025-12-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_alter_review_contacts'),
        ('app_main', '0018_remove_review_contacts_remove_review_rating_and_more'),
    ]

    operations = [
    ]
