# Generated by Django 4.2.19 on 2025-12-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_remove_review_contacts_remove_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1, help_text='Порядок показа услуги в списке услуг', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если отключить, то отзыв не будет показываться. Вместо удаления можно просто отключить видимость', verbose_name='Показывать отзыв ?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.FileField(help_text='Видео отзыв клиента (не больше 20 MB)', null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
