# Generated by Django 4.2.19 on 2025-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0019_merge_20251202_1816'),
        ('app_main', '0019_service_order_alter_review_fullname_and_more'),
    ]

    operations = [
    ]
